export default {
    PRIMARY_COLOR: '#FE9738',
    FONT_SIZE_SMALL: 12,
    FONT_SIZE_MEDIUM: 20,
    FONT_SIZE_LARGE: 30,
    FONT_WEIGHT_LIGHT: '200',
    FONT_WEIGHT_MEDIUM: '500',
    FONT_WEIGHT_BOLD: '700',
    BACKGROUND_COLOR_LIGHT: '#FFFFFF',
    CONTAINER_PADDING: 20,
    TEXT_INPUT_PADDING: 10,
  }